//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Plugin.OAMessage.OAMessage.WebServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OfsTodoDataWebServiceHttpBinding", Namespace="webservices.ofs.weaver.com.cn")]
    public partial class OfsTodoDataWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback receiveRequestInfoByMapOperationCompleted;
        
        private System.Threading.SendOrPostCallback processOverRequestByMapOperationCompleted;
        
        private System.Threading.SendOrPostCallback receiveRequestInfoByXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback processDoneRequestByJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteUserRequestInfoByMapOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteUserRequestInfoByXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback processDoneRequestByXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteRequestInfoByMapOperationCompleted;
        
        private System.Threading.SendOrPostCallback processOverRequestByXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback receiveRequestInfoByJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback receiveTodoRequestByJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteRequestInfoByXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback receiveTodoRequestByXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteUserRequestInfoByJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback processDoneRequestByMapOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteRequestInfoByJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback processOverRequestByJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback receiveTodoRequestByMapOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OfsTodoDataWebService() {
            this.Url = global::Plugin.OAMessage.Properties.Settings.Default.Plugin_OAMessage_OAMessage_WebServices_OfsTodoDataWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event receiveRequestInfoByMapCompletedEventHandler receiveRequestInfoByMapCompleted;
        
        /// <remarks/>
        public event processOverRequestByMapCompletedEventHandler processOverRequestByMapCompleted;
        
        /// <remarks/>
        public event receiveRequestInfoByXmlCompletedEventHandler receiveRequestInfoByXmlCompleted;
        
        /// <remarks/>
        public event processDoneRequestByJsonCompletedEventHandler processDoneRequestByJsonCompleted;
        
        /// <remarks/>
        public event deleteUserRequestInfoByMapCompletedEventHandler deleteUserRequestInfoByMapCompleted;
        
        /// <remarks/>
        public event deleteUserRequestInfoByXMLCompletedEventHandler deleteUserRequestInfoByXMLCompleted;
        
        /// <remarks/>
        public event processDoneRequestByXmlCompletedEventHandler processDoneRequestByXmlCompleted;
        
        /// <remarks/>
        public event deleteRequestInfoByMapCompletedEventHandler deleteRequestInfoByMapCompleted;
        
        /// <remarks/>
        public event processOverRequestByXmlCompletedEventHandler processOverRequestByXmlCompleted;
        
        /// <remarks/>
        public event receiveRequestInfoByJsonCompletedEventHandler receiveRequestInfoByJsonCompleted;
        
        /// <remarks/>
        public event receiveTodoRequestByJsonCompletedEventHandler receiveTodoRequestByJsonCompleted;
        
        /// <remarks/>
        public event deleteRequestInfoByXMLCompletedEventHandler deleteRequestInfoByXMLCompleted;
        
        /// <remarks/>
        public event receiveTodoRequestByXmlCompletedEventHandler receiveTodoRequestByXmlCompleted;
        
        /// <remarks/>
        public event deleteUserRequestInfoByJsonCompletedEventHandler deleteUserRequestInfoByJsonCompleted;
        
        /// <remarks/>
        public event processDoneRequestByMapCompletedEventHandler processDoneRequestByMapCompleted;
        
        /// <remarks/>
        public event deleteRequestInfoByJsonCompletedEventHandler deleteRequestInfoByJsonCompleted;
        
        /// <remarks/>
        public event processOverRequestByJsonCompletedEventHandler processOverRequestByJsonCompleted;
        
        /// <remarks/>
        public event receiveTodoRequestByMapCompletedEventHandler receiveTodoRequestByMapCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="webservices.ofs.weaver.com.cn", ResponseNamespace="webservices.ofs.weaver.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("out", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
        public anyType2anyTypeMapEntry[] receiveRequestInfoByMap([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)] anyType2anyTypeMapEntry[] in0) {
            object[] results = this.Invoke("receiveRequestInfoByMap", new object[] {
                        in0});
            return ((anyType2anyTypeMapEntry[])(results[0]));
        }
        
        /// <remarks/>
        public void receiveRequestInfoByMapAsync(anyType2anyTypeMapEntry[] in0) {
            this.receiveRequestInfoByMapAsync(in0, null);
        }
        
        /// <remarks/>
        public void receiveRequestInfoByMapAsync(anyType2anyTypeMapEntry[] in0, object userState) {
            if ((this.receiveRequestInfoByMapOperationCompleted == null)) {
                this.receiveRequestInfoByMapOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreceiveRequestInfoByMapOperationCompleted);
            }
            this.InvokeAsync("receiveRequestInfoByMap", new object[] {
                        in0}, this.receiveRequestInfoByMapOperationCompleted, userState);
        }
        
        private void OnreceiveRequestInfoByMapOperationCompleted(object arg) {
            if ((this.receiveRequestInfoByMapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.receiveRequestInfoByMapCompleted(this, new receiveRequestInfoByMapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="webservices.ofs.weaver.com.cn", ResponseNamespace="webservices.ofs.weaver.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("out", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
        public anyType2anyTypeMapEntry[] processOverRequestByMap([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)] anyType2anyTypeMapEntry[] in0) {
            object[] results = this.Invoke("processOverRequestByMap", new object[] {
                        in0});
            return ((anyType2anyTypeMapEntry[])(results[0]));
        }
        
        /// <remarks/>
        public void processOverRequestByMapAsync(anyType2anyTypeMapEntry[] in0) {
            this.processOverRequestByMapAsync(in0, null);
        }
        
        /// <remarks/>
        public void processOverRequestByMapAsync(anyType2anyTypeMapEntry[] in0, object userState) {
            if ((this.processOverRequestByMapOperationCompleted == null)) {
                this.processOverRequestByMapOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessOverRequestByMapOperationCompleted);
            }
            this.InvokeAsync("processOverRequestByMap", new object[] {
                        in0}, this.processOverRequestByMapOperationCompleted, userState);
        }
        
        private void OnprocessOverRequestByMapOperationCompleted(object arg) {
            if ((this.processOverRequestByMapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processOverRequestByMapCompleted(this, new processOverRequestByMapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="webservices.ofs.weaver.com.cn", ResponseNamespace="webservices.ofs.weaver.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string receiveRequestInfoByXml([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("receiveRequestInfoByXml", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void receiveRequestInfoByXmlAsync(string in0) {
            this.receiveRequestInfoByXmlAsync(in0, null);
        }
        
        /// <remarks/>
        public void receiveRequestInfoByXmlAsync(string in0, object userState) {
            if ((this.receiveRequestInfoByXmlOperationCompleted == null)) {
                this.receiveRequestInfoByXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreceiveRequestInfoByXmlOperationCompleted);
            }
            this.InvokeAsync("receiveRequestInfoByXml", new object[] {
                        in0}, this.receiveRequestInfoByXmlOperationCompleted, userState);
        }
        
        private void OnreceiveRequestInfoByXmlOperationCompleted(object arg) {
            if ((this.receiveRequestInfoByXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.receiveRequestInfoByXmlCompleted(this, new receiveRequestInfoByXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="webservices.ofs.weaver.com.cn", ResponseNamespace="webservices.ofs.weaver.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string processDoneRequestByJson([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("processDoneRequestByJson", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void processDoneRequestByJsonAsync(string in0) {
            this.processDoneRequestByJsonAsync(in0, null);
        }
        
        /// <remarks/>
        public void processDoneRequestByJsonAsync(string in0, object userState) {
            if ((this.processDoneRequestByJsonOperationCompleted == null)) {
                this.processDoneRequestByJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessDoneRequestByJsonOperationCompleted);
            }
            this.InvokeAsync("processDoneRequestByJson", new object[] {
                        in0}, this.processDoneRequestByJsonOperationCompleted, userState);
        }
        
        private void OnprocessDoneRequestByJsonOperationCompleted(object arg) {
            if ((this.processDoneRequestByJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processDoneRequestByJsonCompleted(this, new processDoneRequestByJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="webservices.ofs.weaver.com.cn", ResponseNamespace="webservices.ofs.weaver.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("out", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
        public anyType2anyTypeMapEntry[] deleteUserRequestInfoByMap([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)] anyType2anyTypeMapEntry[] in0) {
            object[] results = this.Invoke("deleteUserRequestInfoByMap", new object[] {
                        in0});
            return ((anyType2anyTypeMapEntry[])(results[0]));
        }
        
        /// <remarks/>
        public void deleteUserRequestInfoByMapAsync(anyType2anyTypeMapEntry[] in0) {
            this.deleteUserRequestInfoByMapAsync(in0, null);
        }
        
        /// <remarks/>
        public void deleteUserRequestInfoByMapAsync(anyType2anyTypeMapEntry[] in0, object userState) {
            if ((this.deleteUserRequestInfoByMapOperationCompleted == null)) {
                this.deleteUserRequestInfoByMapOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteUserRequestInfoByMapOperationCompleted);
            }
            this.InvokeAsync("deleteUserRequestInfoByMap", new object[] {
                        in0}, this.deleteUserRequestInfoByMapOperationCompleted, userState);
        }
        
        private void OndeleteUserRequestInfoByMapOperationCompleted(object arg) {
            if ((this.deleteUserRequestInfoByMapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteUserRequestInfoByMapCompleted(this, new deleteUserRequestInfoByMapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="webservices.ofs.weaver.com.cn", ResponseNamespace="webservices.ofs.weaver.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string deleteUserRequestInfoByXML([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("deleteUserRequestInfoByXML", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void deleteUserRequestInfoByXMLAsync(string in0) {
            this.deleteUserRequestInfoByXMLAsync(in0, null);
        }
        
        /// <remarks/>
        public void deleteUserRequestInfoByXMLAsync(string in0, object userState) {
            if ((this.deleteUserRequestInfoByXMLOperationCompleted == null)) {
                this.deleteUserRequestInfoByXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteUserRequestInfoByXMLOperationCompleted);
            }
            this.InvokeAsync("deleteUserRequestInfoByXML", new object[] {
                        in0}, this.deleteUserRequestInfoByXMLOperationCompleted, userState);
        }
        
        private void OndeleteUserRequestInfoByXMLOperationCompleted(object arg) {
            if ((this.deleteUserRequestInfoByXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteUserRequestInfoByXMLCompleted(this, new deleteUserRequestInfoByXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="webservices.ofs.weaver.com.cn", ResponseNamespace="webservices.ofs.weaver.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string processDoneRequestByXml([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("processDoneRequestByXml", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void processDoneRequestByXmlAsync(string in0) {
            this.processDoneRequestByXmlAsync(in0, null);
        }
        
        /// <remarks/>
        public void processDoneRequestByXmlAsync(string in0, object userState) {
            if ((this.processDoneRequestByXmlOperationCompleted == null)) {
                this.processDoneRequestByXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessDoneRequestByXmlOperationCompleted);
            }
            this.InvokeAsync("processDoneRequestByXml", new object[] {
                        in0}, this.processDoneRequestByXmlOperationCompleted, userState);
        }
        
        private void OnprocessDoneRequestByXmlOperationCompleted(object arg) {
            if ((this.processDoneRequestByXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processDoneRequestByXmlCompleted(this, new processDoneRequestByXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="webservices.ofs.weaver.com.cn", ResponseNamespace="webservices.ofs.weaver.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("out", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
        public anyType2anyTypeMapEntry[] deleteRequestInfoByMap([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)] anyType2anyTypeMapEntry[] in0) {
            object[] results = this.Invoke("deleteRequestInfoByMap", new object[] {
                        in0});
            return ((anyType2anyTypeMapEntry[])(results[0]));
        }
        
        /// <remarks/>
        public void deleteRequestInfoByMapAsync(anyType2anyTypeMapEntry[] in0) {
            this.deleteRequestInfoByMapAsync(in0, null);
        }
        
        /// <remarks/>
        public void deleteRequestInfoByMapAsync(anyType2anyTypeMapEntry[] in0, object userState) {
            if ((this.deleteRequestInfoByMapOperationCompleted == null)) {
                this.deleteRequestInfoByMapOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteRequestInfoByMapOperationCompleted);
            }
            this.InvokeAsync("deleteRequestInfoByMap", new object[] {
                        in0}, this.deleteRequestInfoByMapOperationCompleted, userState);
        }
        
        private void OndeleteRequestInfoByMapOperationCompleted(object arg) {
            if ((this.deleteRequestInfoByMapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteRequestInfoByMapCompleted(this, new deleteRequestInfoByMapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="webservices.ofs.weaver.com.cn", ResponseNamespace="webservices.ofs.weaver.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string processOverRequestByXml([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("processOverRequestByXml", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void processOverRequestByXmlAsync(string in0) {
            this.processOverRequestByXmlAsync(in0, null);
        }
        
        /// <remarks/>
        public void processOverRequestByXmlAsync(string in0, object userState) {
            if ((this.processOverRequestByXmlOperationCompleted == null)) {
                this.processOverRequestByXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessOverRequestByXmlOperationCompleted);
            }
            this.InvokeAsync("processOverRequestByXml", new object[] {
                        in0}, this.processOverRequestByXmlOperationCompleted, userState);
        }
        
        private void OnprocessOverRequestByXmlOperationCompleted(object arg) {
            if ((this.processOverRequestByXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processOverRequestByXmlCompleted(this, new processOverRequestByXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="webservices.ofs.weaver.com.cn", ResponseNamespace="webservices.ofs.weaver.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string receiveRequestInfoByJson([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("receiveRequestInfoByJson", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void receiveRequestInfoByJsonAsync(string in0) {
            this.receiveRequestInfoByJsonAsync(in0, null);
        }
        
        /// <remarks/>
        public void receiveRequestInfoByJsonAsync(string in0, object userState) {
            if ((this.receiveRequestInfoByJsonOperationCompleted == null)) {
                this.receiveRequestInfoByJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreceiveRequestInfoByJsonOperationCompleted);
            }
            this.InvokeAsync("receiveRequestInfoByJson", new object[] {
                        in0}, this.receiveRequestInfoByJsonOperationCompleted, userState);
        }
        
        private void OnreceiveRequestInfoByJsonOperationCompleted(object arg) {
            if ((this.receiveRequestInfoByJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.receiveRequestInfoByJsonCompleted(this, new receiveRequestInfoByJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="webservices.ofs.weaver.com.cn", ResponseNamespace="webservices.ofs.weaver.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string receiveTodoRequestByJson([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("receiveTodoRequestByJson", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void receiveTodoRequestByJsonAsync(string in0) {
            this.receiveTodoRequestByJsonAsync(in0, null);
        }
        
        /// <remarks/>
        public void receiveTodoRequestByJsonAsync(string in0, object userState) {
            if ((this.receiveTodoRequestByJsonOperationCompleted == null)) {
                this.receiveTodoRequestByJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreceiveTodoRequestByJsonOperationCompleted);
            }
            this.InvokeAsync("receiveTodoRequestByJson", new object[] {
                        in0}, this.receiveTodoRequestByJsonOperationCompleted, userState);
        }
        
        private void OnreceiveTodoRequestByJsonOperationCompleted(object arg) {
            if ((this.receiveTodoRequestByJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.receiveTodoRequestByJsonCompleted(this, new receiveTodoRequestByJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="webservices.ofs.weaver.com.cn", ResponseNamespace="webservices.ofs.weaver.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string deleteRequestInfoByXML([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("deleteRequestInfoByXML", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void deleteRequestInfoByXMLAsync(string in0) {
            this.deleteRequestInfoByXMLAsync(in0, null);
        }
        
        /// <remarks/>
        public void deleteRequestInfoByXMLAsync(string in0, object userState) {
            if ((this.deleteRequestInfoByXMLOperationCompleted == null)) {
                this.deleteRequestInfoByXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteRequestInfoByXMLOperationCompleted);
            }
            this.InvokeAsync("deleteRequestInfoByXML", new object[] {
                        in0}, this.deleteRequestInfoByXMLOperationCompleted, userState);
        }
        
        private void OndeleteRequestInfoByXMLOperationCompleted(object arg) {
            if ((this.deleteRequestInfoByXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteRequestInfoByXMLCompleted(this, new deleteRequestInfoByXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="webservices.ofs.weaver.com.cn", ResponseNamespace="webservices.ofs.weaver.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string receiveTodoRequestByXml([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("receiveTodoRequestByXml", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void receiveTodoRequestByXmlAsync(string in0) {
            this.receiveTodoRequestByXmlAsync(in0, null);
        }
        
        /// <remarks/>
        public void receiveTodoRequestByXmlAsync(string in0, object userState) {
            if ((this.receiveTodoRequestByXmlOperationCompleted == null)) {
                this.receiveTodoRequestByXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreceiveTodoRequestByXmlOperationCompleted);
            }
            this.InvokeAsync("receiveTodoRequestByXml", new object[] {
                        in0}, this.receiveTodoRequestByXmlOperationCompleted, userState);
        }
        
        private void OnreceiveTodoRequestByXmlOperationCompleted(object arg) {
            if ((this.receiveTodoRequestByXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.receiveTodoRequestByXmlCompleted(this, new receiveTodoRequestByXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="webservices.ofs.weaver.com.cn", ResponseNamespace="webservices.ofs.weaver.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string deleteUserRequestInfoByJson([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("deleteUserRequestInfoByJson", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void deleteUserRequestInfoByJsonAsync(string in0) {
            this.deleteUserRequestInfoByJsonAsync(in0, null);
        }
        
        /// <remarks/>
        public void deleteUserRequestInfoByJsonAsync(string in0, object userState) {
            if ((this.deleteUserRequestInfoByJsonOperationCompleted == null)) {
                this.deleteUserRequestInfoByJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteUserRequestInfoByJsonOperationCompleted);
            }
            this.InvokeAsync("deleteUserRequestInfoByJson", new object[] {
                        in0}, this.deleteUserRequestInfoByJsonOperationCompleted, userState);
        }
        
        private void OndeleteUserRequestInfoByJsonOperationCompleted(object arg) {
            if ((this.deleteUserRequestInfoByJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteUserRequestInfoByJsonCompleted(this, new deleteUserRequestInfoByJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="webservices.ofs.weaver.com.cn", ResponseNamespace="webservices.ofs.weaver.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("out", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
        public anyType2anyTypeMapEntry[] processDoneRequestByMap([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)] anyType2anyTypeMapEntry[] in0) {
            object[] results = this.Invoke("processDoneRequestByMap", new object[] {
                        in0});
            return ((anyType2anyTypeMapEntry[])(results[0]));
        }
        
        /// <remarks/>
        public void processDoneRequestByMapAsync(anyType2anyTypeMapEntry[] in0) {
            this.processDoneRequestByMapAsync(in0, null);
        }
        
        /// <remarks/>
        public void processDoneRequestByMapAsync(anyType2anyTypeMapEntry[] in0, object userState) {
            if ((this.processDoneRequestByMapOperationCompleted == null)) {
                this.processDoneRequestByMapOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessDoneRequestByMapOperationCompleted);
            }
            this.InvokeAsync("processDoneRequestByMap", new object[] {
                        in0}, this.processDoneRequestByMapOperationCompleted, userState);
        }
        
        private void OnprocessDoneRequestByMapOperationCompleted(object arg) {
            if ((this.processDoneRequestByMapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processDoneRequestByMapCompleted(this, new processDoneRequestByMapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="webservices.ofs.weaver.com.cn", ResponseNamespace="webservices.ofs.weaver.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string deleteRequestInfoByJson([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("deleteRequestInfoByJson", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void deleteRequestInfoByJsonAsync(string in0) {
            this.deleteRequestInfoByJsonAsync(in0, null);
        }
        
        /// <remarks/>
        public void deleteRequestInfoByJsonAsync(string in0, object userState) {
            if ((this.deleteRequestInfoByJsonOperationCompleted == null)) {
                this.deleteRequestInfoByJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteRequestInfoByJsonOperationCompleted);
            }
            this.InvokeAsync("deleteRequestInfoByJson", new object[] {
                        in0}, this.deleteRequestInfoByJsonOperationCompleted, userState);
        }
        
        private void OndeleteRequestInfoByJsonOperationCompleted(object arg) {
            if ((this.deleteRequestInfoByJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteRequestInfoByJsonCompleted(this, new deleteRequestInfoByJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="webservices.ofs.weaver.com.cn", ResponseNamespace="webservices.ofs.weaver.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string processOverRequestByJson([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0) {
            object[] results = this.Invoke("processOverRequestByJson", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void processOverRequestByJsonAsync(string in0) {
            this.processOverRequestByJsonAsync(in0, null);
        }
        
        /// <remarks/>
        public void processOverRequestByJsonAsync(string in0, object userState) {
            if ((this.processOverRequestByJsonOperationCompleted == null)) {
                this.processOverRequestByJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessOverRequestByJsonOperationCompleted);
            }
            this.InvokeAsync("processOverRequestByJson", new object[] {
                        in0}, this.processOverRequestByJsonOperationCompleted, userState);
        }
        
        private void OnprocessOverRequestByJsonOperationCompleted(object arg) {
            if ((this.processOverRequestByJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processOverRequestByJsonCompleted(this, new processOverRequestByJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="webservices.ofs.weaver.com.cn", ResponseNamespace="webservices.ofs.weaver.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("out", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
        public anyType2anyTypeMapEntry[] receiveTodoRequestByMap([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)] anyType2anyTypeMapEntry[] in0) {
            object[] results = this.Invoke("receiveTodoRequestByMap", new object[] {
                        in0});
            return ((anyType2anyTypeMapEntry[])(results[0]));
        }
        
        /// <remarks/>
        public void receiveTodoRequestByMapAsync(anyType2anyTypeMapEntry[] in0) {
            this.receiveTodoRequestByMapAsync(in0, null);
        }
        
        /// <remarks/>
        public void receiveTodoRequestByMapAsync(anyType2anyTypeMapEntry[] in0, object userState) {
            if ((this.receiveTodoRequestByMapOperationCompleted == null)) {
                this.receiveTodoRequestByMapOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreceiveTodoRequestByMapOperationCompleted);
            }
            this.InvokeAsync("receiveTodoRequestByMap", new object[] {
                        in0}, this.receiveTodoRequestByMapOperationCompleted, userState);
        }
        
        private void OnreceiveTodoRequestByMapOperationCompleted(object arg) {
            if ((this.receiveTodoRequestByMapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.receiveTodoRequestByMapCompleted(this, new receiveTodoRequestByMapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="webservices.ofs.weaver.com.cn")]
    public partial class anyType2anyTypeMapEntry {
        
        private object keyField;
        
        private object valueField;
        
        /// <remarks/>
        public object key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public object value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void receiveRequestInfoByMapCompletedEventHandler(object sender, receiveRequestInfoByMapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class receiveRequestInfoByMapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal receiveRequestInfoByMapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public anyType2anyTypeMapEntry[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((anyType2anyTypeMapEntry[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void processOverRequestByMapCompletedEventHandler(object sender, processOverRequestByMapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processOverRequestByMapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processOverRequestByMapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public anyType2anyTypeMapEntry[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((anyType2anyTypeMapEntry[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void receiveRequestInfoByXmlCompletedEventHandler(object sender, receiveRequestInfoByXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class receiveRequestInfoByXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal receiveRequestInfoByXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void processDoneRequestByJsonCompletedEventHandler(object sender, processDoneRequestByJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processDoneRequestByJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processDoneRequestByJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void deleteUserRequestInfoByMapCompletedEventHandler(object sender, deleteUserRequestInfoByMapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteUserRequestInfoByMapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteUserRequestInfoByMapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public anyType2anyTypeMapEntry[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((anyType2anyTypeMapEntry[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void deleteUserRequestInfoByXMLCompletedEventHandler(object sender, deleteUserRequestInfoByXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteUserRequestInfoByXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteUserRequestInfoByXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void processDoneRequestByXmlCompletedEventHandler(object sender, processDoneRequestByXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processDoneRequestByXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processDoneRequestByXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void deleteRequestInfoByMapCompletedEventHandler(object sender, deleteRequestInfoByMapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteRequestInfoByMapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteRequestInfoByMapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public anyType2anyTypeMapEntry[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((anyType2anyTypeMapEntry[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void processOverRequestByXmlCompletedEventHandler(object sender, processOverRequestByXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processOverRequestByXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processOverRequestByXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void receiveRequestInfoByJsonCompletedEventHandler(object sender, receiveRequestInfoByJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class receiveRequestInfoByJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal receiveRequestInfoByJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void receiveTodoRequestByJsonCompletedEventHandler(object sender, receiveTodoRequestByJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class receiveTodoRequestByJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal receiveTodoRequestByJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void deleteRequestInfoByXMLCompletedEventHandler(object sender, deleteRequestInfoByXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteRequestInfoByXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteRequestInfoByXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void receiveTodoRequestByXmlCompletedEventHandler(object sender, receiveTodoRequestByXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class receiveTodoRequestByXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal receiveTodoRequestByXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void deleteUserRequestInfoByJsonCompletedEventHandler(object sender, deleteUserRequestInfoByJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteUserRequestInfoByJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteUserRequestInfoByJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void processDoneRequestByMapCompletedEventHandler(object sender, processDoneRequestByMapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processDoneRequestByMapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processDoneRequestByMapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public anyType2anyTypeMapEntry[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((anyType2anyTypeMapEntry[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void deleteRequestInfoByJsonCompletedEventHandler(object sender, deleteRequestInfoByJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteRequestInfoByJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteRequestInfoByJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void processOverRequestByJsonCompletedEventHandler(object sender, processOverRequestByJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processOverRequestByJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processOverRequestByJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void receiveTodoRequestByMapCompletedEventHandler(object sender, receiveTodoRequestByMapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class receiveTodoRequestByMapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal receiveTodoRequestByMapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public anyType2anyTypeMapEntry[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((anyType2anyTypeMapEntry[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591