//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Web.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 绝对时间超时 的本地化字符串。
        /// </summary>
        internal static string AbsoluteTimeExpired {
            get {
                return ResourceManager.GetString("AbsoluteTimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能根据登录名&quot;{0}&quot;找到用户 的本地化字符串。
        /// </summary>
        internal static string CanNotFindUser {
            get {
                return ResourceManager.GetString("CanNotFindUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能从当前线程或HttpContext中取得用户的登录和权限信息(Principal) 的本地化字符串。
        /// </summary>
        internal static string CanNotGetPrincipal {
            get {
                return ResourceManager.GetString("CanNotGetPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法从url或cookie中得到有效的ticket 的本地化字符串。
        /// </summary>
        internal static string CanNotGetTicket {
            get {
                return ResourceManager.GetString("CanNotGetTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 认证服务器不匹配 的本地化字符串。
        /// </summary>
        internal static string DifferentAthenticateServer {
            get {
                return ResourceManager.GetString("DifferentAthenticateServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前Windows帐号的域名是&quot;{0}&quot;，应该是&quot;{1} 的本地化字符串。
        /// </summary>
        internal static string DomainNameMismatch {
            get {
                return ResourceManager.GetString("DomainNameMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在角色判断时，提供的应用、角色字符串格式不正确。正确的格式应该为(应用的名称1:角色名称11,角色名称12,...;应用名称2:角色名称21,角色名称22,...) 的本地化字符串。
        /// </summary>
        internal static string InvalidAppRoleNameDescription {
            get {
                return ResourceManager.GetString("InvalidAppRoleNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP不正确 的本地化字符串。
        /// </summary>
        internal static string IPInvalid {
            get {
                return ResourceManager.GetString("IPInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能得到当前访问页面的用户ID，请检查IIS设置中，该页面是否禁止匿名访问 的本地化字符串。
        /// </summary>
        internal static string PageMustForbidAnonymousAccess {
            get {
                return ResourceManager.GetString("PageMustForbidAnonymousAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数&quot;{0}&quot;是认证服务的保留字，请不要在url中包含&quot;{0}&quot;参数 的本地化字符串。
        /// </summary>
        internal static string ParamIsReserved {
            get {
                return ResourceManager.GetString("ParamIsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties 的本地化字符串。
        /// </summary>
        internal static string SignInInfoExtraProperties {
            get {
                return ResourceManager.GetString("SignInInfoExtraProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相对时间超时 的本地化字符串。
        /// </summary>
        internal static string SlidingTimeExpired {
            get {
                return ResourceManager.GetString("SlidingTimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户&quot;{0}&quot;的ticket失效，原因为{1} 的本地化字符串。
        /// </summary>
        internal static string TicketInvalidReason {
            get {
                return ResourceManager.GetString("TicketInvalidReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passport 的本地化字符串。
        /// </summary>
        internal static string TranslateCategory {
            get {
                return ResourceManager.GetString("TranslateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户&apos;{0}&apos;认证失败，请检查用户名和密码是否正确。 的本地化字符串。
        /// </summary>
        internal static string UserAuthenticateFail {
            get {
                return ResourceManager.GetString("UserAuthenticateFail", resourceCulture);
            }
        }
    }
}
